# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/campus_placement_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings (Tables khud banayega)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# EMAIL CONFIGURATION (JavaMailSender)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# NEECHAY APNI ASLI GMAIL ID LIKHEIN (Jaise: akram@gmail.com)
spring.mail.username=aapki.asli.id@gmail.com 

# NEECHAY GOOGLE KA 16-DIGIT APP PASSWORD LIKHEIN BINA SPACE KE (Jaise: abcdefghijklmnop)
spring.mail.password=yahan_16_digit_app_password_likhein

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true